from app.models.user import User
from app.models.teacher import Teacher
from app.models.student import Student
from app.models.school_class import SchoolClass
from app.models.subject import Subject
from app.models.schedule import Schedule
from app.models.attendance import Attendance
from app.models.score import Score
from app.models.homework import Homework
from app.models.homework_submission import HomeworkSubmission
from app.models.notification import Notification
from app.models.event import Event
from app.models.holiday import Holiday
from app.models.parent import Parent
from app.models.parent_student import ParentStudent